import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import NotificationSection from '@/components/NotificationSection';
import Header from '@/components/Header';

const inter = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <main className='h-screen w-screen overflow-hidden flex bg-[#f5f6fa] '>
          <div className='flex-grow p-8'>
            <Header />
            {children}
          </div>
          <NotificationSection />
        </main>
      </body>
    </html>
  );
}
